### PR TITLE
Composer support, output destination, manual package declaration and more

### PR DESCRIPTION
**Pull request by christophermancini**

### CODE REVIEW

**Comment by christophermancini** [comment]
I have made many, many improvements to the parser for the lib that I would like to get merged but this has sat here so long that now it conflicts with the main branch. Seeking a review of my work and advice on how to get this PR merged.

**Comment by hjagodzinski** [comment]
I'm working on a PR that will introduce a lot of changes regarding a compilation and a class generation. I have already [mentioned](#71) about it. I plan to merge it shortly in a week or so. This change will solve most of the issues you encountered.

I'm really sorry nobody responded to your PR earlier. I'm doing my best lately to bring this project alive. It's hard as I don't have much time on my hands. First I want to fix long standing issues frequently reported. Then review pull requests including PHP 7 support.

**Comment by christophermancini** [comment]
So let me know how I can help. Here is a list of the big items that I have implemented with my changes and let me know which ones you have completed or are completing. Then I can migrate my work to your latest change set.

- Added composer support
- Moved the parser script to /bin, removed the php extension and added a shebang
- Added verbose mode
- Added output directory
- Added the ability for the parser to look for imports relative to the source file
- Added package override
- Moved file output to a single function for code reuse
- Added better regex parsing for whitespaces
- Added support for multi-line comment stripping
- Fixed misc spelling errors in README
- Added code to prevent reserved keywords from being used as field names

**Comment by hjagodzinski** [comment]
I haven't made this clear but I decided to do my own change because I wanted to fix compiler issues as it should be done by providing the protoc plugin. The parsing is done by the protoc which supports protocol buffers syntax fully including the new kid in the block - syntax 3.

The things that seems to me to remain valid in your pull request are:
* Added composer support (I use composer to manage the dependencies of the plugin)
* Fixed misc spelling errors in README
* Added code to prevent reserved keywords from being used as field names

Once I create a pull request it would be great if someone could code review and test it. Any help would be appreciated.

I understand this project is important for you and why you want write permissions. Nevertheless I'm afraid it might not be possible to grant you them. Still someone else needs to take a look at pull request and approve it. I will try to be more helpful here and keep this project live so any pull request and any issue get handled sooner that it used to be.

**Comment by christophermancini** [comment]
@hjagodzinski I completely understand and I would never YOLO a merge, its not how I do things for any of the other community projects I maintain.

**Comment by hjagodzinski** [comment]
@christophermancini what would you like to do with this pull request? A lot of has changed lately in php-protobuf and the only thing that is still valid is composer support.

**Comment by hjagodzinski** [comment]
The #95 has been just merged providing composer support.

**Comment by christophermancini** [comment]
At some point in the near future, I will test your latest changes with https://github.com/basho/riak-phppb-client and submit any further PRs based on the latest code base.

**Comment by hjagodzinski** [comment]
Sounds great, thanks!

**Pull request closed without merging**
